before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarm:
      - '7'
    mod_timestamp: '{{ .CommitTimestamp }}'
    id: dexctl
    main: ./cmd/dexctl
    binary: dexctl
    ldflags:
      - -s -w
      - -X github.com/rudeigerc/dexctl/pkg/cmd/version.gitVersion={{ .Version }}
      - -X github.com/rudeigerc/dexctl/pkg/cmd/version.gitCommit={{ .Commit }}
      - -X github.com/rudeigerc/dexctl/pkg/cmd/version.buildDate={{ .CommitDate }}
archives:
  - id: dexctl
    format: binary
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  - name: dexctl
    tap:
      owner: rudeigerc
      name: homebrew-tap
    commit_author:
      name: rudeigerc
      email: rudeigerc@gmail.com
    folder: Formula
    goarm: '7'
    homepage: https://github.com/rudeigerc/dexctl
    description: A command line tool for Dex IdP gRPC interface
    license: Apache-2.0
    dependencies:
      - name: go
        type: build
    test: |
      system "#{bin}/dexctl version --client"
